/* Copyright 2022 Google LLC. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/


// load image data
window.initExport = function(){

  var sel = d3.select('#export').html('')
    .on('click', function(){

      var range = document.createRange()
      range.selectNode(this)
      window.getSelection().removeAllRanges()
      window.getSelection().addRange(range)
    })
    .append('pre')

  function update(){
    var text = `# click on an image to generate code`

    var colorArray = scales.active.samples.slice(0, config.nSamples)
      .map(d => d.concat(255))

    text = `
# ${scales.active.name} colormap generated by github.com/PAIR-code/colormap

flatcolors = np.array([${colorArray}])
colors = np.reshape(flatcolors, (4, -1)) / 255.0
newcmp = ListedColormap(colors)

# TODO data transform/brush

# TODO contrast/brightness

# TODO plot code
    `.trim()

  sel.text(text)
  }



  return {update, debouncedUpdate: _.debounce(update, 0)}
}

if (window.init) init()

